### ISSUE TITLE
VTYSH：command erro

### ISSUE THREAD

**Issue by Yanjinux** [open-switch/ops-classifierd#2]
hi 
    When I enter     `switch (config) # access-list ip My_ACL` , the following is displayed:(config) the following is displayed:
`
(none)(config)# access-list ip My_ACL
ready is false
setting the latch
temp is null
cur_cfg_no
cur_cfg_no 1
ovsdb cfg init success
% Command failed.
`
 What is the problem?
                                                                                                                                                   thank

**Comment by jeff-yin** [comment]
Closing issue as this repo is no longer being actively developed or supported.
