### ISSUE TITLE
Warning: testACL user configuration does not match active configuration.

### ISSUE THREAD

**Issue by Yanjinux** [open-switch/ops-classifierd#3]
I accoding to http://git.openswitch.net/cgit/openswitch/ops/tree/docs/access_list_user_guide.md 。The procedure is as follows：
`   switch(config)# access-list ip testACL

Add one or more entries to the list:

    switch(config-acl)# 10 permit udp any 172.16.1.0/24
    switch(config-acl)# 20 permit tcp 172.16.2.0/16 gt 1023 any
    switch(config-acl)# 30 deny any any any count
    switch(config-acl)# exit

Apply the ACL to an interface:

    switch(config)# interface 1
    switch(config-if)# apply access-list ip testACL in
    switch(config-if)# exit
`

but when i enter
    show access-list interface 1 in
As shown below：
% Warning: testACL user configuration does not match active configuration.
%          run 'reset access-list all' to reset acce
-----------------------------------------------------------------------------------------------------------

**Comment by jeff-yin** [comment]
Closing issue as this repo is no longer being actively developed or supported.
